#!/bin/sh -e

if ! command -v cosmocc > /dev/null
then
	echo "You need to add cosmopolitan toolchain to your path:"
	echo "export PATH=\$PATH:<path-to-cosmopolitan>/bin"
	exit 1
fi

COSMO_HOME=$(dirname $(dirname $(which cosmocc)))

FLAGS="-I deps/sokol \
	-I deps/cimgui \
	-mcosmo \
	-mtiny \
	-Wall \
	-Werror"

LINUX_FLAGS="${FLAGS} -Ishims/linux"

WIN32_FLAGS="${FLAGS} -Ishims/win32 -I ${COSMO_HOME}/include/libc/nt"

mkdir -p .build
mkdir -p bin

COMPILE=scripts/compile

$COMPILE shims/sokol/sokol_windows.c ${WIN32_FLAGS}
$COMPILE shims/sokol/sokol_linux.c ${LINUX_FLAGS}
$COMPILE shims/sokol/sokol_shared.c ${FLAGS}
$COMPILE shims/sokol/sokol_cosmo.c ${FLAGS}

$COMPILE deps/cimgui/cimgui.cpp ${FLAGS}
$COMPILE deps/cimgui/imgui/imgui.cpp ${FLAGS}
$COMPILE deps/cimgui/imgui/imgui_demo.cpp ${FLAGS}
$COMPILE deps/cimgui/imgui/imgui_draw.cpp ${FLAGS}
$COMPILE deps/cimgui/imgui/imgui_tables.cpp ${FLAGS}
$COMPILE deps/cimgui/imgui/imgui_widgets.cpp ${FLAGS}

$COMPILE shims/linux/gl.c ${LINUX_FLAGS}
$COMPILE shims/linux/x11.c ${LINUX_FLAGS}

$COMPILE main.c ${FLAGS}

objects=$(find .build -name '*.o' -not -path '*.aarch64/*')
cosmoc++ ${FLAGS} -o bin/cosmo-sokol $objects
